variable "vm_name" {}
variable "resource_group_name" {}
variable "location" {}
variable "size" {}
variable "computer_name" {}
variable "os_disk_name" {}
variable "publisher" {}
variable "offer" {}
variable "sku" {}
variable "version1" {}
variable "key_vault_name" {}
variable "username_secret_key" {}
variable "pwd_secret_key" {}
variable "nic_name" {}